params:
  batch_size: 512
  mini_batch_size: 128
  total_timesteps: 100_000
  epochs: 5
  actor_loss_clip: 0.2
  gae_gamma: 0.99 
  gae_lambda: 0.95
  actor_lr: 0.0001
  critic_lr: 0.001
exp:
  seed: 3
  torch_deterministic: True