params:
  batch_size: 256
  mini_batch_size: 64
  total_timesteps: 100_000
  epochs: 8
  actor_loss_clip: 0.2
  critic_loss_clip: 0.2
  gae_gamma: 0.99 
  gae_lambda: 0.95
  actor_lr: 0.0003
  critic_lr: 0.0003
  max_grad_norm: 0.5
exp:
  model_dir: weights
  seed: 23
  torch_deterministic: True