defaults:
  - override hydra/job_logging: colorlog
  - override hydra/hydra_logging: colorlog
  - _self_
dataset:
  path: /nfs_home/janhavi2021/spring2021/tabTransformer/data/Telco-Customer-Churn.csv
params:
  batch_size: 32
  num_epochs: 30
  train_size: 0.8